default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Instagramclone_development

test:
  <<: *default
  database: Instagramclone_test

production:
  <<: *default
  database: Instagramclone_production
  username: Instagramclone
  password: <%= ENV['INSTAGRAMCLONE_DATABASE_PASSWORD'] %>
